# Estudo de TensorFlow

Varios exemplos de probramas para estudo da ferramenta.

1. https://juliocprocha.wordpress.com/2017/08/28/uma-introducao-ao-tensorflow-e-suas-operacoes-basicas/

In [76]:
import tensorflow as tf
import numpy as np
 
#Primeiro definimos os números
 
#criamos uma constante.
x_1 = tf.constant(2.0,dtype=tf.float32)
 
#A função tf.constant cria nossas constantes
x_2 = tf.constant(5.0,dtype=tf.float32)
 
#Aqui multiplicamos os dois resultados.
mult = x_1*x_2
 
#Aqui somamos as duas constante
soma = x_1+x_2
 
# Toda vez que quisermos executar usamos o método run
# Isso nos permite compilar e executar o código solicitado.
sess = tf.Session()
 
#Aqui executamos a multiplicação
print(sess.run(mult))
 
#Aqui executamos a soma.
print(sess.run(soma))

10.0
7.0


### Operações com vetores

In [77]:
#criamos uma variável constante.
vetor_1 = tf.constant([2.0,3.0,7.0],dtype=tf.float32)
 
#A função tf.constant cria nossas constantes
vetor_2 = tf.constant([5.0,2.0,6.0],dtype=tf.float32)
 
#Aqui multiplicamos os dois vetores
#Utilizei as funções multply e reduce_sum.
#multply: multplica duas array elemento por elemento.
#reduce_sum: faz o somatório dos elementos de um vetor
mult = tf.reduce_sum(tf.multiply(vetor_1,vetor_2))
 
#Aqui somamos os dois vetores de forma tradicional
soma = vetor_1+vetor_2
 
# Toda vez que quisermos execultar o métono run
# Isso nos permite compilar e execultar o codigo solicitado.
sess = tf.Session()
 
#Aqui execultamos a multiplicação
print(sess.run(mult))
 
#Aqui execultamos a soma.
print(sess.run(soma))

58.0
[ 7.  5. 13.]


###  função tf.add

Nesse exemplo duas variáveis $x_{1}$ e  $x_{2}$ entram como input e são somadas e logo depois gerado o output.
 ![Alt text](https://juliocprocha.files.wordpress.com/2017/08/imagem_6.png)


In [78]:
#tf.placeholder funciona como um input.
#isso quer dizer que essas variáveis virão de fora
x_1 = tf.placeholder(dtype=tf.float32)
 
#Aqui os valores entrarão somente ná hora que
# forem execultados.
x_2 = tf.placeholder(dtype=tf.float32)
 
output = tf.add(x_1,x_2)
 
# Toda vez que quisermos execultar o métono run
# Isso nos permite compilar e execultar o codigo solicitado.
sess = tf.Session()
 
#Aqui execultamos a soma.
#Repare que passamos os valores para os placeholders na forma
# de um dict. Eu acho isso interessante pois facilita a comunicação
# com a API.
print(sess.run(output,{x_1:1,x_2:2}))

3.0


----

Nesse caso temos uma estrutura semelhante ha de uma rede neural artificial, claro falta algumas coisas, mas como o foco é o processamento da informação isso não é um problema.

Numerei os Nodes de 1 a 3 os inputs entram e são somados em cada Node e depois o resultado de cada um é multiplicado por uma constante e o output sai no utimo Node.

![Alt text](https://juliocprocha.files.wordpress.com/2017/08/imagem_71.png)


In [79]:
#Vamos declarar os inputs
x_1 = tf.placeholder(dtype=tf.float32)
 
x_2 = tf.placeholder(dtype=tf.float32)
 
#Crio o primeiro Node
#Ele soma os dois inputs
Node_1 = tf.add(x_1,x_2)
 
#Crio o segundo Node
Node_2 = tf.add(x_1,x_2)
 
#No terceiro Node esses valores entram Multplicados
#Pelos seus respectivos pesos
Node_3 = tf.add(Node_1*2,Node_2*5)
 
# Toda vez que quisermos execultar o métono run
# Isso nos permite compilar e execultar o codigo solicitado.
sess = tf.Session()
 
#Aqui execultamos a soma.
#Repare que passamos os valores para os placeholders na forma
# de um dict.
print(sess.run(Node_3,{x_1:8,x_2:9}))

119.0


### Fim 1


### Inicio 2

https://juliocprocha.wordpress.com/2017/11/21/multilayer-perceptron-com-tensorflow/

![Alt text](https://juliocprocha.files.wordpress.com/2017/11/imagem_1.jpg)


In [80]:
import tensorflow as tf
 
#Usaremos o pandas para algumas transformações basicas
import pandas as pd
 
#Numpy apenas para deixar as coisas mais rapidas
import numpy as np
 
#Irei utilizar essa função do sklearn para dividir o conjunto de treino e teste
from sklearn.cross_validation import train_test_split



import seaborn as sns

from bokeh.sampledata.iris import flowers as dados

data=dados

In [81]:


#Definimos essa função para normalizar o coluna Species
#Exemplo [preto,branco,preto,azul] => [0,1,0,2]
def normalizeIris(x):
    if x == "virginica":
        return 0
    elif x == "versicolor":
        return 1
    else:
        return 2
 
#fazemos a função para transforma as labels em one-hot vectors
#Exemplo [1,2,1,0] => [[0,1,0],[0,0,1],[0,1,0],[1,0,0]]
def makeHotvector(y_data):
    labels = []
    for x in range(len(y_data)):
        labels.append([0,0,0])
        labels[x][y_data[x]] = 1
    y_data = np.array(labels,dtype=np.float64)
    return y_data






#Usamos o método .apply do Pandas para aplicar a função normaLizeIris
#Na coluna "Species" lembre o que essa função faz
data["species"] = data["species"].apply(normalizeIris)
 
#Aqui separamos as features em uma variavel e as labels em outra
x_data = data.drop("species",axis=1).values
y_data = data["species"].values
 
#Aqui separamos um pouco do dataset para treino e a outra parte para teste
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.2)

Agora iremos começar a arquitetar a rede. Nossa rede possui dois hidden layers, o primeiro com 5 Nodes e o segundo com 3 Nodes, 4 inputs e 3 outputs como mostrado no esquema abaixo.

![Alt text](https://juliocprocha.files.wordpress.com/2017/11/imagem_2.png)

Essa não é a rede mais apropriada para esse tipo de problema, pois estamos lidando com uma tarefa de classificação de múltiplas classes, porem já que se trata de um dataset simples é perfeitamente possível treinarmos usando apenas a função logística sigmoide.

Obs: Na prática é muito comum colocar uma função softmax na saída da rede.

Se você reparou, acima transformamos os dados em one-hot-vectors, isso significa que cada output tem que ser um vetor do tipo [1,0,0],[0,1,0],[0,0,1] representando respectivamente a espécies 0, 1 e 2.

Essa estratégia de treino é chamada one-vs-rest assim podemos treinar a rede para fazer aproximações de um output específico.

Isso dito vamos começar a montar nossa rede, o primeiro passo é definir alguns parâmetros.

In [82]:
#A quantidade inputs na rede
n_input = 4
#A proporção em que a rede irá atualizar cada peso
#Chamamos também de alpha
learning_rate = 0.01
# A quantidade de unidades no primeiro layer
n_hidden_unites_1 = 5
#A quantidade de unidades no segundo layer
n_hidden_unites_2 = 3


In [83]:
#Vamos criar o grapho da rede
#Primeiro definimos a sessão
sess = tf.Session()

In [84]:
#Aqui são os inputs da rede
#Apenas os inputs do dataset são considerados.
X = tf.placeholder(shape=[None,n_input],dtype=tf.float64)
 
#Aqui ficam as Labels para treino
#Essa parte do grafo não aparece no esquema.
#mas aqui fica as labels que serão usadas como exemplo para a rede.
y_ =  tf.placeholder(dtype=tf.float64)

![](https://juliocprocha.files.wordpress.com/2017/11/imagem_3.png)


In [85]:
#Agora iremos definir os pesos da rede
#Esse é nosso primeira camada de pesos.
W = {"h1":tf.Variable(tf.random_normal([n_input,n_hidden_unites_1],dtype=tf.float64),dtype=tf.float64),
     "h2":tf.Variable(tf.random_normal([n_hidden_unites_1,n_hidden_unites_2],dtype=tf.float64),dtype=tf.float64)
    }

Os pesos nada mais são do que matrizes com o número de linhas igual ao número de inputs e o número de coluna igual a quantidade de unidades no primeiro hidden-layer.

![](https://juliocprocha.files.wordpress.com/2017/11/imagem_41.png)


In [86]:
#Esse é o bias da rede
b = {"b1":tf.Variable(tf.random_normal([n_hidden_unites_1],dtype=tf.float64),dtype=tf.float64),
     "b2":tf.Variable(tf.random_normal([n_hidden_unites_2],dtype=tf.float64),dtype=tf.float64)
    }

![](https://juliocprocha.files.wordpress.com/2017/11/imagem_5.png)


Agora definimos as funções de ativação de cada camada. como se trata de um problema simples usaremos somente a sigmoide.

In [87]:
#Sigmoide aplicado a rede
#O output do hidden_1
out_hidden_1 = tf.nn.sigmoid(tf.matmul(X,W["h1"])+b["b1"])
#o output do hidden_2 que alias será o usado como nosso output.
out_hidden_2 = tf.nn.sigmoid(tf.matmul(out_hidden_1,W["h2"])+b["b2"])


Podemos ver a representação no esquema.

![](https://juliocprocha.files.wordpress.com/2017/11/imagem_6.png)

Isso definido vamos cuidar do treino dessa rede.

No caso o que temos abaixo é uma média do erro do output da rede em relação a label usada como exemplo, usamos isso para orientar a atualização dos pesos na rede.

In [88]:
#Definimos o erro quadratico do out_hidden_2 em relação y_
#isso permite deriva-lo e depois ajustar os pesos
mse = tf.losses.mean_squared_error(y_,out_hidden_2)
 
#Aqui eu uso o método gradientDescent para otimizar o parametro mse
#Ele ira derivar o erro em relação a cada pesso da rede e fazer um atualização
#para cima ou para abaixo proporcional ao learning_hate da rede
train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(mse)


In [89]:
#Aqui iremos inicializar todas as variaveis que compõe o grafo.

#Uma maneira de carregar as variaveis para a memoria.
init = tf.global_variables_initializer()
sess.run(init)

Isso permite ao TensorFlow inicializar todas as operações que compoe o grafo gerando assim o output.

Agora vem uma das partes mais importantes que é a forma que a rede ira ser treinada. Eu escolhi um loop dentro de um loop onde o algoritmo treina de forma incremental exemplo por exemplo (online learning.) porem de maneira aleatória.

In [93]:
#Realizar 1000 interações no dataset
for x in range(100):
    print(x)#para ver o andamento do treino
 
    #Iremos dar loop do tamanho do dataset
    for _ in range(len(x_train)):
        #Aqui seleciono uma instancia aliatória do dataset
        i = np.random.randint(len(x_train))
        x = np.array([x_train[i]])
        y = np.array([y_train[i]])
 
        #Aqui treinamos a rede uma iteração de cada vez
        train_step.run(feed_dict={X:x,y_:y},session=sess)



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


Observe a forma que a rede é treinada. Ela minimiza o erro exemplo por exemplo isso é conhecido camo Stochastic gradient descent.

Depois de treinar a rede podemos ver alguns indices básicos de acuracia.

In [94]:
#Aqui iremos medir a precisão do modelo
#colocamos a rede para validar os outputs no conjunto de teste
outputs = out_hidden_2.eval(feed_dict={X:x_test},session=sess)
 
#Aqui convertemos de one-hot-vector para discreto
labels = [x.argmax() for x in y_test]
predictions = [x.argmax() for x in outputs]
 
#aplicamos confusion matrix para ver o desepenho
cm = confusion_matrix(labels,predictions)
 
#aqui vemos a acuracia do algoritmo.
acuracy = accuracy_score(labels,predictions)
 
print(cm)
print(acuracy)

[[ 4 22  4]
 [ 0  0  0]
 [ 0  0  0]]
0.13333333333333333
