# Matrizes

In [2]:
import numpy as np

a= np.array([[5,4,7],[0,3,4],[0,0,6]])

In [3]:
print(a)

[[5 4 7]
 [0 3 4]
 [0 0 6]]


In [5]:
joao= [20,30,40,15]
pedro= [100,24,48,23]
maria=[92,22,34,12]
marcos=[12,23,12,43]

In [6]:
pontos= np.array([joao,pedro,maria,marcos])

In [7]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  23,  12,  43]])

In [9]:
my_data = np.arange(0,20)
my_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
mat1= np.reshape(my_data,(5,4)) #Transformando vetor em matriz
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  23,  12,  43]])

In [13]:
pontos.item(5) #Seleciona elementos em uma matriz

24