In [1]:
import numpy as np

In [3]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [4]:
m2/m1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [7]:
np.matrix.round(m2/m1)

array([[7., 4., 3.],
       [2., 2., 2.]])

In [9]:
m1+10

array([[11, 12, 13],
       [14, 15, 16]])

In [10]:
(m1+5)==(m2-1)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [11]:
m1**2

array([[ 1,  4,  9],
       [16, 25, 36]])