In [1]:
import numpy as np

In [3]:
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a[a>3]

array([4, 5, 6])

In [5]:
a[a>1]

array([2, 3, 4, 5, 6])

In [6]:
a[a>4].sum()

SyntaxError: invalid syntax (<ipython-input-6-fc3a989e70b6>, line 1)