In [4]:
import numpy as np

In [7]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [8]:
type(a)

numpy.ndarray

In [11]:
mat = np.array([[1,2],[3,4]])
mat

array([[1, 2],
       [3, 4]])

In [12]:
print(mat[-1][-1])

4


In [13]:
mat[1]

array([3, 4])

In [15]:
mat[:,0]#Primeira Coluna

array([1, 3])

In [17]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [19]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
m1+m2

array([[ 6,  8],
       [10, 12]])

In [20]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [22]:
m3 = np.array([1,2,3,4])
m3.sum

<function ndarray.sum>